import Link from 'next/link'
import { BookOpen } from 'lucide-react'

export const metadata = {
  title: 'Terms & Privacy — LearnLab AI',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-cloud px-6 py-10">
      <div className="mx-auto max-w-2xl">
        {/* Back link */}
        <Link
          href="/"
          className="mb-8 flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"
        >
          <div className="flex h-6 w-6 items-center justify-center rounded-md bg-navy">
            <BookOpen className="h-3.5 w-3.5 text-white" />
          </div>
          LearnLab AI
        </Link>

        <h1 className="mb-1 text-2xl font-bold text-navy">Terms of Use &amp; Privacy</h1>
        <p className="mb-8 text-sm text-muted-foreground">Effective: June 2026</p>

        {/* Terms of Use */}
        <section className="mb-8">
          <h2 className="mb-3 text-base font-semibold text-navy">Terms of Use</h2>
          <div className="flex flex-col gap-4 text-sm text-foreground/80 leading-relaxed">
            <p>
              <strong>Portfolio project.</strong> LearnLab AI is a personal portfolio demonstration
              and is provided free of charge for educational use only. It is not a commercial
              product and comes with no service-level guarantee.
            </p>
            <p>
              <strong>Permitted use.</strong> You may use this app to generate study aids —
              quizzes, flashcards, summaries, lesson plans, and study schedules — from your own
              study materials. Use is personal and non-commercial only.
            </p>
            <p>
              <strong>AI-generated content.</strong> All output is generated by an AI model
              (Anthropic Claude) and may contain errors, omissions, or inaccuracies.{' '}
              <strong>Always verify AI-generated content against your textbook or a trusted
              source.</strong> LearnLab AI accepts no liability for inaccuracies in generated
              content.
            </p>
            <p>
              <strong>Derivative outputs.</strong> Quizzes, summaries, flashcards, and lesson
              plans generated from your uploaded material are derivative works. You are responsible
              for ensuring you have the right to process and generate study aids from any content
              you upload.
            </p>
            <p>
              <strong>Acceptable use.</strong> Do not use this service to generate or seek
              harmful, illegal, or age-inappropriate content. Content safety guardrails are in
              place; attempts to bypass them may result in the request being refused.
            </p>
            <p>
              <strong>Minors.</strong> This app is designed to be safe for students of all
              ages, including minors. All AI outputs are filtered for age-appropriateness.
              Minors should use the service with their guardian&apos;s awareness.
            </p>
          </div>
        </section>

        <hr className="mb-8 border-border" />

        {/* Privacy */}
        <section className="mb-8">
          <h2 className="mb-3 text-base font-semibold text-navy">Privacy Policy</h2>
          <div className="flex flex-col gap-4 text-sm text-foreground/80 leading-relaxed">
            <p>
              <strong>No personal information by default.</strong> When you first visit, a
              random anonymous user ID is created and stored locally in your browser. No name,
              email, phone number, or other personally identifiable information is collected
              unless you choose to enable cross-device sync (see below).
            </p>
            <p>
              <strong>Uploaded files.</strong> Files you upload (PDF, DOCX, images) are
              transmitted securely to cloud storage solely for text extraction. Once the text
              has been extracted and saved, <strong>the original file is deleted</strong> from
              storage. Files are never shared with third parties, indexed, or retained beyond
              the extraction step.
            </p>
            <p>
              <strong>Study data.</strong> Quizzes, flashcard decks, summaries, lesson plans,
              scores, and study plans are stored in a database keyed to your anonymous user ID.
              This data is only accessible to you and is isolated from other users by
              database-level access controls.
            </p>
            <p>
              <strong>Cross-device sync (optional).</strong> If you choose to use LearnLab on
              more than one device, you may optionally link an email address to your account.
              This is entirely opt-in. Your email is used only to authenticate you on a second
              device — it is not used for marketing, sharing with third parties, or any purpose
              other than account access. Without linking an email, your data remains
              device-local and no personal information is collected.
            </p>
            <p>
              <strong>Browser storage.</strong> Supabase (our database and auth provider)
              stores your session token in your browser&apos;s{' '}
              <code className="rounded bg-muted px-1 py-0.5 text-xs">localStorage</code>. This
              is the only data stored in your browser. Clearing your browser storage will end
              your current session and start a new anonymous one.
            </p>
            <p>
              <strong>Third-party services.</strong> This app uses Anthropic Claude (AI
              generation), Supabase (database, storage, and authentication), and Vercel
              (hosting). Each has its own privacy policy. Text extracted from your uploaded
              content is sent to Anthropic&apos;s API for generation; it is not used to train
              Anthropic&apos;s models under the standard API terms.
            </p>
            <p>
              <strong>Data retention &amp; deletion.</strong> Your study data persists on this
              device (or across devices if you link an email) until you clear your browser
              storage or sign out. For anonymous accounts with no linked email, data may be
              periodically purged after extended inactivity (portfolio service, no uptime
              guarantee).
            </p>
            <p>
              <strong>Contact.</strong> This is a portfolio project. For questions, open an
              issue on the project&apos;s public repository.
            </p>
          </div>
        </section>

        <hr className="mb-6 border-border" />
        <p className="text-xs text-muted-foreground">
          These terms apply to the LearnLab AI portfolio demo. They may be updated without
          notice. Continued use constitutes acceptance of any changes.
        </p>
      </div>
    </div>
  )
}
